### ISSUE TITLE
Support /command@YourBot style commands

### ISSUE THREAD

**Issue by miikka** [Otann/morse#12]
If there are multiple bots in a group, [you can disambiguate commands](https://core.telegram.org/bots#commands) by postfixing the command with bot's @username, e.g. `/command@YourBot`. When autocompleting a command (if you have told Telegram about your bot's commands via `/setcommands` to BotFather), Telegram does this automatically.

It'd be great if `morse.handlers/command` would support this out of the box. If I understand [Telegram's FAQ](https://core.telegram.org/bots/faq#what-messages-will-my-bot-get) correctly, you won't ever get messages that were meant for other bots in the group, even if your bot is not in the privacy mode. This means morse could just split the received commands on `@` and match on the first part - there's no need to know the bot's username.

**Comment by Otann** [comment]
That is a wonderful idea, thank you! 
I will try to implement it in next couple of weeks, but can't promise anything.
Also PRs are much welcomed ;)

**Comment by deril** [comment]
Fixed in #14

**Comment by miikka** [comment]
#14 is included in version 0.2.4. Seems to work.
