### ISSUE TITLE
Global timeout outside of clj-http for getting updates in the polling process.

### ISSUE THREAD

**Issue by dixel** [Otann/morse#31]
Running a telegram-bot in a long-polling mode I sometimes experienced a complete freeze of the polling process.
According to some issues I had in the past, clj-http doesn't usually handle timeouts in an expected way, probably mainly because of this issue in JDK: https://bugs.openjdk.java.net/browse/JDK-8075484.
Having some external timeout that could inform the user application can be quite useful in such scenarios, but obviously would be good to address this issue to the maintainers of clj-http as well.

**Comment by Otann** [comment]
Released `0.3.2` to Clojars with your fix, thank you for the PR!
