### ISSUE TITLE
Got HTTP request timed out

### ISSUE THREAD

**Issue by evilsneer** [Otann/morse#35]
after switching on 0.3.4 version for handling 502 error i've got an another frustrating bug

> фев 23, 2018 10:49:53 AM morse.polling invoke
> SEVERE: HTTP request timed out, stopping polling

i've just strarted pooling as 
`(<!! (p/start token handler))`

please help=)

**Comment by evilsneer** [comment]
fixed it by adding timeout opts to p/start
like this 
`(<!! (p/start token handler {:timeout 30}))`

**Comment by Otann** [comment]
For some reason, telegram's API was not as precise with time and doubled timeout happened before morse gets a response from telegram.
 
I've bumped timeout for hack ten times and released a quick fix as `[morse "0.3.6"]`
