### ISSUE TITLE
hellonico/morse 0.2.4 ?

### ISSUE THREAD

**Issue by zackteo** [Otann/morse#54]
What happened to https://github.com/otann/morse/commit/908b07b615d4a5bc035c46893c72d770bf27f92f ? (Which is used for https://libraries.io/clojars/hellonico%2Fmorse) 

Some features like download-file in api are implemented in hello-nico but not in the supposedly updated morse repo here? :o

**Comment by marksto** [comment]
Hi @zackteo!

The commit you've linked here does not belong to any branch on this repository and belongs to an outside fork. Thus, you'd better contact the developers of this repository for an answer to your question. And AFAICS the merge you asked about was done in the opposite direction (original repo -> fork repo), so no changes from the fork repo could get here.

Cheers,
Mark
